### ISSUE TITLE
when using curent version of emby the following is in the embylog and does not work

### ISSUE THREAD

**Issue by DomenicTroilo** [crobibero/Emby.Plugins.LazyMan#18]
*** Error Report ***
        Version: 4.3.1.0
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby-server -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
        Operating system: Unix 5.4.13.0
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
        Processor count: 16
        Program data path: /var/lib/emby-server
        Application directory: /opt/emby-server/system
        System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
           at Emby.Server.Implementations.Library.MediaSourceManager.GetLiveStreamWithDirectStreamProvider(String id, CancellationToken cancellationToken)
           at Emby.Server.Implementations.Library.MediaSourceManager.GetLiveStream(String id, CancellationToken cancellationToken)
           at Emby.Server.Implementations.Library.MediaSourceManager.GetMediaSource(BaseItem item, String mediaSourceId, String liveStreamId, Boolean enablePathSubstitution, CancellationToken cancellationToken)
           at Emby.Server.Implementations.Session.SessionManager.UpdateNowPlayingItem(SessionInfo session, PlaybackProgressInfo info, BaseItem libraryItem, Boolean updateLastCheckInTime)
           at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
           at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
        Source: Emby.Server.Implementations
        TargetSite: Void MoveNext()

**Comment by crobibero** [comment]
What version of the plugin are you using?
What Date / Game / Stream / Quality did you attempt to play?
