### ISSUE TITLE
Running Emby through a VPN container

### ISSUE THREAD

**Issue by stevenjev** [crobibero/Emby.Plugins.LazyMan#19]
I currently connect the network of my Emby docker container through a VPN container. When refreshing internet channels, I get this error: 

    *** Error Report ***
	Version: 4.4.0.16
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 5.4.0.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 6
	Program data path: /config
	Application directory: /system
	System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
	   at System.Net.Dns.InternalGetHostByName(String hostName)
	   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
	   at Emby.Plugins.LazyMan.Utils.PingTest.IsMatch(String testHost, ILogger logger)
	   at Emby.Plugins.LazyMan.LazyManChannel.<GetSportFolders>b__19_0(String domain)
	   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
	   at Emby.Plugins.LazyMan.LazyManChannel.GetSportFolders()
	   at Emby.Plugins.LazyMan.LazyManChannel.GetChannelItems(InternalChannelItemQuery query, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItems(IChannel channel, String externalFolderId, Nullable`1 sortField, Boolean sortDescending, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItemsInternal(Channel channel, IChannel channelProvider, InternalItemsQuery query, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Channels.ChannelManager.GetAllItems(Channel channel, IChannel channelProvider, Int64 parentId, Int32 currentRefreshLevel, Int32 maxRefreshLevel, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Channels.ChannelManager.RefreshChannel(Tuple`2 channelTuple, CancellationToken cancellationToken)
	Source: System.Net.NameResolution
	TargetSite: System.Net.IPHostEntry InternalGetHostByName(System.String)

I'm assuming it is related to the `pingTestDomains` function, where it tests the three hosts because If I manually change those to the IP address that is returned when pinging, the error goes away, and the channels are loaded. However, no video plays. The Linux host running Emby and the VPN has an updated /etc/hosts file which contains the correct hosts, and the VPN docker container contains the correct additional host file entries. Is there no way around requiring the hosts? Could I manually write them in the code and just recompile the source each time the IP addresses are updated?

**Comment by crobibero** [comment]
As far as I know there is no way around requiring the host edit. 
Can you add logs of when you're trying to play a game with the hosts manually set? Your VPN might be blocking connection to the required host.

**Comment by stevenjev** [comment]
Further investigation.. I was running the latest beta branch of Emby through Linuxserver.io. This doesn't load any of the streams but dropping down to the latest release allows streams to load through the VPN.

**Comment by crobibero** [comment]
Ok good to know, I'll likely have to make changes to support the latest Emby release
