### ISSUE TITLE
Emby will not play feed anymore

### ISSUE THREAD

**Issue by MaDTaZ** [crobibero/Emby.Plugins.LazyMan#20]
For a while now When I choose a game I see the 760p and all that but when i go to play them they will not load.

Any ideas

Using the new plugin and emby is updated to the newest

**Comment by MaDTaZ** [comment]
This can be closed I didnt see the update from 13 days ago

**Comment by MaDTaZ** [comment]
Emby Version 4.4.0.23 beta and just added the new update for the plug in. Can not get it to start the feed

**Comment by Lanageddon** [comment]
Im currently unable to play anything, MLB,NHL, highlights etc. Using the latest release 8.0 with Emby Beta 4.4.0.23 on windows 10 with the client being a roku tv. It used to show the network name now everything just says Audio-Away/Home or NHLTV-Away/Home.

**Comment by crobibero** [comment]
Please try latest release. https://github.com/crobibero/Emby.Plugins.LazyMan/releases/tag/v9.0.0

**Comment by Lanageddon** [comment]
All feeds say Not available yet No compatible stream.

**Comment by crobibero** [comment]
@Lanageddon Make sure to run the "Refresh Internet Channels" scheduled task. I'm currently watching via the plugin on the latest stable emby.

**Comment by jordandev** [comment]
Installed 9.0.0 and restarted Emby and now the plugin doesn't show up at all. Emby 4.3.1.0

**Comment by crobibero** [comment]
@jordandev the latest release is for emby v4.4+

**Comment by Lanageddon** [comment]
I now get an error Playback error - Too many errors. Moving on... but on the dashboard it says its direct playing.

I guess ill just have to go back to the stable version.

**Comment by jordandev** [comment]
Whoops, my bad, 9.0.0 now shows up on 4.4.0.23 beta.

The games show up but the feed will not start "Playback Error. No compatible streams are currently available"

Which was the original reason I tried 9.0.0 because 8.0.0 was not loading the feed with 4.3.1.0 for me either (it would just drop back to the game list).

**Comment by Lanageddon** [comment]
@jordandev I went back to 4.3 with version 8.0 and now everything works for me.

**Comment by MaDTaZ** [comment]
> @jordandev I went back to 4.3 with version 8.0 and now everything works for me.

Can I just install 4.3 over the beta version?

**Comment by jordandev** [comment]
Went back to 8.0.0 and emby 4.3.1.0 and the feeds still don't load.

I'm getting this error in the log:

`2020-03-10 18:58:31.179 Info App: ProcessRun 'StreamTranscode de1638' Execute: C:\Users\Jordan\AppData\Roaming\Emby-Server\system\ffmpeg.exe -loglevel +timing -i "https://hlslive-l3c.med2.med.nhl.com/token=exp=1583977205~id=nhlGatewayId:5028558~data=71372303~hash=da69227e4ba722399ad41915fc67e63e24da4108/ls03/nhl/2020/03/10/NHL_GAME_VIDEO_CARDET_M2_HOME_20200310_1582066321138/1800K/1800_slide.m3u8" -map_metadata -1 -map_chapters -1 -threads 0 -sn -c:v:0 libx264 -pix_fmt yuv420p  -maxrate 139808000 -bufsize 279616000 -preset veryfast -profile:v:0 high -level:v:0 4.1 -crf 23 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -vsync -1 -codec:a:0 ac3 -disposition:a:0 default -ac:a:0 6 -ab:a:0 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_write_temp 1 -segment_list_entry_prefix "hls/f0b7b5b50c3b7d0c4b51fa8e0aecf167/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "C:\Users\Jordan\AppData\Roaming\Emby-Server\programdata\transcoding-temp\f0b7b5b50c3b7d0c4b51fa8e0aecf167.m3u8" -y "C:\Users\Jordan\AppData\Roaming\Emby-Server\programdata\transcoding-temp\f0b7b5b50c3b7d0c4b51fa8e0aecf167%d.ts"
2020-03-10 18:58:36.890 Info App: ProcessRun 'StreamTranscode de1638' Process exited with code 1
2020-03-10 18:58:36.918 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.3.1.0
	Command line: C:\Users\Jordan\AppData\Roaming\Emby-Server\system\EmbyServer.dll
	Operating system: Microsoft Windows NT 6.2.9200.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///C:/Users/Jordan/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: C:\Users\Jordan\AppData\Roaming\Emby-Server\programdata
	Application directory: C:\Users\Jordan\AppData\Roaming\Emby-Server\system
	System.Exception: System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.BaseHlsService.ProcessRequest(StreamRequest request)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()`

**Comment by MaDTaZ** [comment]
> Please try latest release. https://github.com/crobibero/Emby.Plugins.LazyMan/releases/tag/v9.0.0

I put the new version in 9.0 with 4.4.0.23 restarted and then ran the scheduled task to refresh channels 

Still not working and the error appears quicker now.

**Comment by crobibero** [comment]
> > Please try latest release. https://github.com/crobibero/Emby.Plugins.LazyMan/releases/tag/v9.0.0
> 
> I put the new version in 9.0 with 4.4.0.23 restarted and then ran the scheduled task to refresh channels
> 
> Still not working and the error appears quicker now.

Feel free to actually tell me what the error you’re getting is.

**Comment by MaDTaZ** [comment]
> > > Please try latest release. https://github.com/crobibero/Emby.Plugins.LazyMan/releases/tag/v9.0.0
> > 
> > 
> > I put the new version in 9.0 with 4.4.0.23 restarted and then ran the scheduled task to refresh channels
> > Still not working and the error appears quicker now.
> 
> Feel free to actually tell me what the error you’re getting is.

Sorry forgot that part lol.

So I get all the feeds 
Click on a game and choose the 720 0r 720 60
Get a spinning wheel for about 1-2 and then the below
Playback Error
No compatible streams are currently available. Please try again later or contact your system administrator for details.

2020-03-10 19:08:14.872 Debug LazyManChannel: [GetStreamUrlAsync] Getting stream url from: https://{0}/getM3U8.php?league=nhl&date=2020-03-10&id=71591503&cdn=l3c
2020-03-10 19:08:14.872 Info HttpClient: GET https://freegamez.ga/getM3U8.php?league=nhl&date=2020-03-10&id=71591503&cdn=l3c
2020-03-10 19:08:15.723 Debug LazyManChannel: [GetStreamUrlAsync] ResponseCode: OK
2020-03-10 19:08:15.723 Debug LazyManChannel: [GetStreamUrlAsync] Response: https://hlslive-l3c.med2.med.nhl.com/token=exp=1583978760~id=nhlGatewayId:5028558~data=71591503~hash=28df34371cbfe219ce69bce764c2a98223b7e9ca/ls03/nhl/2020/03/10/NHL_GAME_VIDEO_BOSPHI_M2_HOME_20200310_1583854817039/master_wired60.m3u8

**Comment by crobibero** [comment]
@MaDTaZ as far as I can tell the plugin is working correctly. Do you have your hosts set correctly?

**Comment by MaDTaZ** [comment]
@crobibero Yes I will not post it but reminder I have the same setup on the same computer for Jellyfin
